### ISSUE TITLE
Package download error

### ISSUE THREAD

**Issue by hardcodet** [taskforcesh/bullmq-pro-support#41]
Wanted to perform fresh package install, but yarn failed on the bullmq download. Is this a hiccup, or did anything change?

```
➤ YN0035: │ @taskforcesh/bullmq-pro@npm:^5.1.10: The remote server failed to provide the requested resource
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.yarnpkg.com/@taskforcesh%2fbullmq-pro
```

My `package.json` and `.npmrc` files didn't change.

Thanks for your advice

**Comment by manast** [comment]
Seems like it is a misconfiguration in your .npmrc since it is trying to fetch it from a different repo: https://registry.yarnpkg.com/

**Comment by hardcodet** [comment]
Ah, identified the issue: It's a fresh windows install, and Yarn 2 doesn't recognize `.npmrc` anymore - the registry needs to be declared in a `yarnrc.yml` file.

If anybody else stumbles over that issue, here's the contents of my `yarnrc.yml` file:

```
nodeLinker: node-modules

npmScopes:
  taskforcesh:
    npmAlwaysAuth: true
    npmAuthToken: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    npmRegistryServer: "https://npm.taskforce.sh/"
```
